# Generated by Django 4.1.5 on 2023-02-06 01:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('user_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('refferal_ID', models.CharField(default='3A18230206', max_length=255, unique=True)),
                ('referal_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_referral_bonus_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_referral_bonus_withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_reffered', models.IntegerField(default=0, null=True)),
                ('reffered_by', models.CharField(default='', max_length=225, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='ReferralsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reffered_by', models.CharField(max_length=225)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('rewarded', 'Rewarded'), ('not_rewarded', 'Not Rewarded')], default='', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.users')),
            ],
        ),
    ]
